
 development:
    adapter: postgresql
    username: Andy
    host: localhost
    encoding: UTF8

development:
  <<: *default
  database: Andy

test:
  <<: *default
  database: db/test.postgresql

production:
  <<: *default
  database: db/production.postgresql
