
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tofu_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: tofu_test
  host: localhost
  port: 5432

production:
  <<: *default
  database: tofu_production
  username: tofu
  password: <%= ENV['FOS_DATABASE_PASSWORD'] %>
